sensors:
  # - id: 1
  #   position: [0.00, 0.00, 0.00]
  #   orientation: [0.0, 0.0, 0.0] # RPY格式 (单位: rad)
  # - id: 2
  #   position: [0.001, 0.00, 0.00]
  #   orientation: [0.0, 0.0, 0.0]


  - id: 1
    position: [0.00, 0.04, 0.00]
    orientation: [0.0, 0.0, 0.0] # RPY格式 (单位: rad)
  - id: 2
    position: [0.01, 0.04, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 3
    position: [0.02, 0.04, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 4
    position: [0.03, 0.04, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 5
    position: [0.04, 0.04, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 6
    position: [0.00, 0.03, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 7
    position: [0.01, 0.03, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 8
    position: [0.02, 0.03, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 9
    position: [0.03, 0.03, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 10
    position: [0.04, 0.03, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 11
    position: [0.00, 0.02, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 12
    position: [0.01, 0.02, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 13
    position: [0.02, 0.02, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 14
    position: [0.03, 0.02, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 15
    position: [0.04, 0.02, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 16
    position: [0.00, 0.01, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 17
    position: [0.01, 0.01, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 18
    position: [0.02, 0.01, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 19
    position: [0.03, 0.01, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 20
    position: [0.04, 0.01, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 21
    position: [0.00, 0.00, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 22
    position: [0.01, 0.00, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 23
    position: [0.02, 0.00, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 24
    position: [0.03, 0.00, 0.00]
    orientation: [0.0, 0.0, 0.0]
  - id: 25
    position: [0.04, 0.00, 0.00]
    orientation: [0.0, 0.0, 0.0]
