estimator_config:
  # 基础配置
  estimator_type: optimization

  # 磁铁参数配置
  magnet:
    strength: 10
    strength_delta: 0
    direction: [0, 0, 1]
    position: [0.01, 0.01, 0.01]

  # 基础优化参数配置（基线方案）
  optimization:
    max_iterations: 50             # 基础迭代次数
    function_tolerance: 1.0e-12    # 更严格的函数收敛条件
    gradient_tolerance: 1.0e-14    # 更严格的梯度收敛条件
    parameter_tolerance: 1.0e-12   # 更严格的参数收敛条件
    num_threads: 1
    minimizer_progress_to_stdout: true  # 开启详细输出，观察收敛过程
    
    linear_solver_type: "DENSE_QR"        # 基础线性求解器
    use_huber_loss: false                 # 不使用鲁棒损失函数
    enable_multi_stage: false             # 不使用多阶段优化
    cost_threshold: 1000.0                # 高阈值，基本不触发重优化

