# 仿真相关配置
simulation_config:
  # 磁铁参数配置
  magnet:
    strength: 10 # 磁矩大小，单位：安培·米² (A·m²)
    direction: [0, 0, 1] # 磁矩方向向量，指向z轴正方向

  # 运动路径参数
  path:
    # 矩形路径尺寸
    width: 0.03 # 宽度，单位：m（3厘米）
    height: 0.03 # 高度，单位：m（3厘米）
    z: 0.03 # 平面高度，单位：m（3厘米）

    # 矩形路径中心位置
    center:
      x: 0.02 # x坐标，单位：m（2厘米）
      y: 0.02 # y坐标，单位：m（2厘米）

    # 运动控制参数
    update_rate: 100.0 # 位置更新频率，单位：Hz
    points_per_side: 500 # 每条边的路径点数量

  # 磁铁运动模式配置
  motion:
    mode: "translate_only"  # 运动模式: "translate_and_rotate", "translate_only", "rotate_only", "static"
    
    # 旋转参数（仅在rotate_only或translate_and_rotate模式下有效）
    axis: "z"              # 旋转轴: "x", "y", "z", "xyz"
    angular_velocity: 5  # 角速度，单位：rad/step
    initial_pitch: 0.5     # 初始俯仰角，单位：rad
    initial_roll: 0.0      # 初始滚转角，单位：rad
    initial_yaw: 0.0       # 初始偏航角，单位：rad
      
    # 静态模式参数（仅在static模式下有效）
    static_position: [0.02, 0.02, 0.03]  # 固定位置 [x, y, z]，单位：m
    static_orientation: [0.0, 0.5, 0.0]  # 固定朝向 [roll, pitch, yaw]，单位：rad

  # 噪声参数
  noise:
    enable: false # 是否添加噪声
    type: gaussian # 噪声类型，可选: gaussian, uniform
    mean: 0.0 # 均值
    stddev: 1000.0 # 标准差（高斯噪声用）
    amplitude: 1.0 # 幅值（均匀噪声用）

