# 离线 CSV 可视化
# 默认扫描输出 CSV，可在 bringup 里覆盖到 data/scan_data.csv
# 如果指定 subfolder，会使用 data/{subfolder}/scan_data.csv
# 如果 subfolder 为空，会自动使用最新的时间戳文件夹
csv_path: data/scan_data.csv
subfolder: ""  # 留空表示自动使用最新文件夹，或指定如 "scan_20251023_1800"
frame: world
marker_topic: /field_map_csv/markers
field_scale: 0.03
marker_lifetime: 0.0  # 0表示永久显示，适合离线可视化
color_max: 50.0
stride: 1   # 可设置>1进行抽稀
