# 在线聚合整图（3D体积）
# 全部为私有命名空间参数（~）

# 订阅原始传感器话题（单位 mT）
topic: /mag_sensor/data_mT
# 聚合输出基坐标
frame: world
# 发布的可视化 topic
marker_topic: /mag_viz/markers

# 扫描体积范围（与控制端一致，可在此更改）
volume_min: [0.3, -0.2, 0.8]
volume_max: [0.5, 0.2, 1.3]
step: [0.05, 0.05, 0.05]

# 可视化参数
field_scale: 0.05           # 箭头长度缩放
marker_lifetime: 5.0        # s，在线刷新建议较短
color_max: 50.0             # mT，最大色标；可在结果出来后调大/调小
publish_stride: 1           # 抽稀绘制步长（>1可加速）

# 导出整图采样 CSV（会被时间戳目录覆盖）
export_csv: placeholder.csv
# 输出基目录（时间戳文件夹将创建在此目录下）
output_base_dir: data
