# 默认扫描体积与步长（米），以及姿态 yaw（弧度）
frame_id: world
yaw: 0.0
pitch: -3.14159  # 添加 pitch 参数，-pi 表示末端朝下
autostart: true

# 传感器配置
mag_topic: "/mag_sensor/raw_data_mT"
wait_time: 2.0  # 移动到位置后的等待时间（秒）
output_file: "/tmp/scan_data.csv"

# 体积边界（min <= xyz <= max）
volume_min: [0.3, -0.2, 1.0]
volume_max: [0.5, 0.2, 1.3]

# 步长（每轴间隔）
step: [0.05, 0.05, 0.05]

