log4j.logger.ros.moveit_core=WARN
log4j.logger.ros.moveit_ros_planning=WARN
log4j.logger.ros.moveit_ros_move_group=WARN
log4j.logger.ros.moveit_planners_ompl=WARN
log4j.logger.ros.moveit_ros_planning_interface=WARN
log4j.logger.ros.moveit_ros_perception=WARN
log4j.logger.ros.moveit_fake_controller_manager=WARN
log4j.logger.ros.moveit_simple_controller_manager=WARN
log4j.logger.ros.moveit_ros_control_interface=WARN
log4j.logger.ros.moveit_controller_manager=WARN
